# Introduction To NumPy

 1. What's NumPy and why numpy arrays?
 2. Creating arrays from python lists(or other iterables)
 3. Creating arrays using built-in methods (quite a few!)
 4. Shape and Reshape


In [ ]:
import numpy as np

In [ ]:

a = [1,2,3,4,5,6]

print(type(a))

import numpy as np

print(set(a))
 
#numpy array
print(np.array(a))

print(type(np.array(a)))

# Two dimensional array or Matrix

matrix = [[1,2,3],[4,5,6],[7,8,9]]

print(matrix)

print(np.array(matrix))

print(np.array((1,2,3,4,5)))

print(np.array(range(10)))

print(np.array(range(1,10,2)))

np.array({1,2,3})

np.array(list({1,2,3}))


<class 'list'>
{1, 2, 3, 4, 5, 6}
[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
{1, 2, 3}
[1 2 3]


In [8]:
np.array({'a':1, 'b':2})

array({'a': 1, 'b': 2}, dtype=object)

##### Arange

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

It is automatically convert or handle data to the same types

In [ ]:
np.array([0,0,0,0,0,1.])

array([0, 0, 0, 0, 0, 1])

In [27]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.zeros((3,3,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [31]:
np.ones(3)

array([1., 1., 1.])

In [173]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Numpy Array 2

linespace : linear spacing between start and end values( both inclusive)

linspace(start, stop, num)

Step= stop−start
	
----------

num -1​


In [44]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [47]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

eye( n * n)

In [ ]:
# matrix n*n
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.eye(2,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.]])

In [57]:
np.eye(5,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

generate random number

rand, randn, randint

In [62]:
np.random.rand(5) # uniform distribution over [0,1]

array([0.47517605, 0.17812925, 0.32020939, 0.80846489, 0.20817175])

In [92]:
np.random.rand(3,5)

array([[0.84684803, 0.39203457, 0.27334233, 0.41814495, 0.42435112],
       [0.96513388, 0.21533441, 0.97582097, 0.05929856, 0.52703643],
       [0.50935714, 0.9566619 , 0.04023584, 0.4499295 , 0.43298736]])

In [95]:
np.random.randn(100) # normal distribution 

array([ 0.728548  , -0.74769739, -1.3735509 ,  2.47312704, -0.36071071,
       -1.66582375,  0.49039506,  0.16707232,  0.48397643, -1.52210549,
       -0.49268536,  0.92027296, -1.99308162, -1.20228022, -0.49652934,
       -0.16160876, -2.38624803, -0.57785153, -0.52672288, -0.62785153,
        1.10155166, -0.23958945,  0.04424432,  0.19565535,  0.89155675,
       -0.3023329 ,  0.90661564,  0.89411401, -2.10756846, -1.03819726,
       -0.632251  , -2.18487454,  0.55632341,  0.41911646, -1.56214336,
        0.75630232, -0.34476616, -0.79195272, -0.09415743,  2.48210198,
        1.45645915,  0.26309746, -1.33855977,  0.82061381, -0.21553209,
       -1.01001118, -0.14637259, -0.49132754, -0.37530641, -0.97820073,
        0.21254678,  2.28228595, -0.13913472,  1.03362744,  0.07548134,
       -0.07587213, -0.39160148,  1.09804072, -0.07161058,  0.3044067 ,
        0.0064795 ,  0.17028386,  0.44538328, -0.99078363,  1.10407079,
        0.58618742, -1.36460584, -0.00384743,  1.16223124, -0.26

In [97]:
np.random.randn(3,5)

array([[-0.51192567,  0.45014522, -0.73061826, -1.78087843,  0.51693709],
       [ 0.48388066, -0.69805743,  0.81785058,  0.86473557, -0.72015032],
       [-0.09967571, -1.42151842, -0.22654982, -2.33425207,  0.18032646]])

In [155]:
np.random.randint(0,10)

8

Exercise 

Create a 5x5 matrix with each item = 0.5

In [175]:
np.ones((5,5))*.5

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]])

In [ ]:
np.zeros(((5,5)))+0.5 

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]])

In [212]:
arr = np.arange(24)

In [213]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### Reshape can shape the arr in numpy

reshape( shape, order)

In [220]:
arr.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [223]:
arr.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [229]:
porhay = arr.reshape(2,2,3,2)

shape will tell you what is just reshape arr

In [230]:
porhay.shape

(2, 2, 3, 2)

Accessing to Data

In [231]:
arr[4] 

np.int64(4)

In [232]:
arr[-1]

np.int64(23)

In [ ]:
arr2 = arr.reshape(4,6)

In [234]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
arr2[1]

array([ 6,  7,  8,  9, 10, 11])

In [238]:
arr2[1][4]

np.int64(10)

In [ ]:

arr2[1, -2]

np.int64(10)

In [242]:
arr2[(1,-2)]

np.int64(10)

In [244]:
print(arr2[(1, 4)])

10


In [245]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [248]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [250]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [255]:
arr2[1:3, 1:3]

array([[ 7,  8],
       [13, 14]])

Change the order

In [259]:
arr2[::-1, ::-1]

array([[23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [261]:
arr2[::-1][::-1]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
arr2[::-1][::-1]

array([[18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

### more array operation: full, copy, concatenate

In [265]:
np.ones((3,3))*0.5

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [266]:
x= np.full( (3,3),0.5)

In [267]:
x

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [269]:
x[0,0] =1

In [283]:
x[0:3,0:2] = 0

In [284]:
x

array([[0. , 0. , 0.5],
       [0. , 0. , 0.5],
       [0. , 0. , 0.5]])

In [289]:
x[0:3, 0:2] = np.zeros((3,2))

In [290]:
x

array([[0. , 0. , 0.5],
       [0. , 0. , 0.5],
       [0. , 0. , 0.5]])

In [293]:
x2 = x[0:2, 0:2].copy()

In [294]:
x2

array([[0., 0.],
       [0., 0.]])

In [296]:
x2[0,0] =3

In [297]:
x2

array([[3., 0.],
       [0., 0.]])

In [298]:
x

array([[0. , 0. , 0.5],
       [0. , 0. , 0.5],
       [0. , 0. , 0.5]])

In [304]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [305]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr2d = np.array([[1,2,3], [4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [308]:
arr2d2 = np.array([[1,2,3], [4,5,6]]) *2

arr2d2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [309]:
np.concatenate([arr2d,arr2d2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 2,  4,  6],
       [ 8, 10, 12]])

In [312]:
np.concatenate([arr2d,arr2d2], axis = 1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12]])

array([1, 2, 3, 4])

In [321]:
x.reshape(1,4)

array([[1, 2, 3, 4]])

In [322]:
y

array([5, 6, 7, 8])

In [324]:
np.concatenate([x.reshape(1,4), y.reshape(1,4)], axis = 0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [326]:
a1 = np.ones((2,3))
a2 = np.ones((2,2))*0.5

In [328]:
a1


array([[1., 1., 1.],
       [1., 1., 1.]])

In [329]:
a2

array([[0.5, 0.5],
       [0.5, 0.5]])

In [333]:
np.concatenate([a1,a2],axis = 1)

array([[1. , 1. , 1. , 0.5, 0.5],
       [1. , 1. , 1. , 0.5, 0.5]])

## Universal function (ufuncs)

vectorized solution

In [352]:
import numpy as np 
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/ values[i]
    return output


values = np.random.randint(1,10, size =5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [353]:
values

array([6, 1, 4, 4, 8])

In [362]:
big_array = np.random.randint(1,100, size = 1000000)

In [364]:
compute_reciprocals(big_array) 

array([0.01886792, 0.0625    , 0.03703704, ..., 0.04      , 0.125     ,
       0.01086957])

In [365]:
%timeit compute_reciprocals(big_array)

933 ms ± 4.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [366]:
values

array([6, 1, 4, 4, 8])

In [367]:
1/values

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [368]:
1/big_array

array([0.01886792, 0.0625    , 0.03703704, ..., 0.04      , 0.125     ,
       0.01086957])

In [370]:
%timeit 1/big_array

834 μs ± 76.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [371]:
np.divide(1, big_array)

array([0.01886792, 0.0625    , 0.03703704, ..., 0.04      , 0.125     ,
       0.01086957])

In [372]:
m1 = np.arange(25).reshape(5,5)

In [373]:
m2 = np.arange(1,26).reshape(5,5)

In [374]:
m1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [375]:
m2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [376]:
m1/m2

array([[0.        , 0.5       , 0.66666667, 0.75      , 0.8       ],
       [0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ],
       [0.90909091, 0.91666667, 0.92307692, 0.92857143, 0.93333333],
       [0.9375    , 0.94117647, 0.94444444, 0.94736842, 0.95      ],
       [0.95238095, 0.95454545, 0.95652174, 0.95833333, 0.96      ]])

In [377]:
m1 * 2


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [378]:
m2 + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [387]:
def myPi(n):
    x = 0
    while n > 0:
        x += ((-1)**(n+1))/(2*n-1)
        n -= 1
    return 4 * x


In [388]:
%timeit myPi(100000)

22.3 ms ± 315 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [389]:
myPi2 = lambda n: 4*np.sum(((-1) ** (np.arange(1, n+1) +1)) / (2*np.arange(1,n+1)-1) )

In [390]:
%timeit myPi2(1000000)

13.8 ms ± 425 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [391]:
myPi2(1000000)

np.float64(3.141591653589794)

In [392]:
np.abs(-1)

np.int64(1)

In [393]:
lambda p, q : np.sum(np.abs( p-q ))

<function __main__.<lambda>(p, q)>

Broadcasting

In [394]:
np.ones((3,3)) + np.full((3,3),0.5)

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

In [403]:
np.ones((3,3)) + np.full((3,1),0.5)

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

In [ ]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Rule 1 : if the two arrays differ in their number of dimensions, the shape of the one with fewer dimension is padded with ones on its leading (left) side.

Rule 2 : if the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape

Rule 3 : if in any dimension the sizes disagree and neither is equal to 1, an error is raised.

### masking

In [409]:
x = np.array([-1,3,2,-4,5,7])

In [410]:
x 

array([-1,  3,  2, -4,  5,  7])

In [411]:
x < 0

array([ True, False, False,  True, False, False])

In [412]:
x > 0

array([False,  True,  True, False,  True,  True])

In [413]:
x ==3

array([False,  True, False, False, False, False])

In [415]:
y = np.arange(25).reshape(5,5)

In [417]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [418]:
np.sum(y>20)

np.int64(4)

In [419]:
y%2==0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [420]:
np.sum(y%2==0, axis = 1)

array([3, 2, 3, 2, 3])

In [423]:
np.all(y>= 10)

np.False_

In [424]:
np.any(y>20)

np.True_

In [425]:
np.sum((y>10) & (y<20))

np.int64(9)

### fancy indexing

In [426]:
x = np.random.randint(100, size =100)


In [427]:
x

array([ 1, 79, 93, 59, 88, 32, 75, 54, 36, 68, 58, 55, 10, 19,  7, 56, 66,
       67, 51, 35, 34, 21, 20, 99, 11, 31,  0, 65, 74, 12, 62,  4, 57, 77,
       37, 23,  7,  0, 38, 61, 61, 20, 80, 55, 88, 44, 63, 64, 42, 48, 44,
       21, 35, 92, 73, 89, 10, 65, 86, 34, 90, 17,  0, 51, 71, 43, 96, 39,
       95, 12, 91, 23, 53, 83, 73, 35, 48, 55, 77,  0, 13, 58, 90,  2, 25,
       52, 33, 84, 12, 72, 82, 62, 70, 96, 25, 55, 26, 63, 41,  1])

In [428]:
[x[1], x [-1], x [5]]

[np.int64(79), np.int64(1), np.int64(32)]

In [431]:
y = np.random.randint(100, size=24).reshape(4,6)

In [432]:
y

array([[ 6, 25, 29, 24, 75, 84],
       [84, 55, 98, 46, 95,  5],
       [55, 99, 38,  7, 83,  3],
       [60, 96, 46, 48, 79, 74]])

In [435]:
y[1:3, 1:3]

array([[55, 98],
       [99, 38]])

In [434]:
y[[1,0] , [5,4]]

array([ 5, 75])

In [443]:
import numpy as np 
arr = np.array(np.arange(25)).reshape(5, 5) 
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [444]:
x = np.arange(101)

x1 = x + 7

In [445]:
x1

array([  7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,
        20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
        33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
        46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
        59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 103, 104, 105, 106, 107])

In [ ]:
np.array(np.ones((10))*8)

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [472]:
arr = np.arange(20,30)

result = arr %2 == 0

arr[result]

array([20, 22, 24, 26, 28])

In [ ]:
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [477]:
np.random.randn(10)

array([-1.57026017, -1.30065262, -1.07667786, -0.56316899, -0.11697359,
        0.00880583,  1.16002659,  1.04155279,  0.12616263,  0.05270977])

In [479]:
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
arr = np.arange(1,26).reshape(5,5)
matrix = arr[2:4,1:4] 

matrix

array([[12, 13, 14],
       [17, 18, 19]])

In [506]:
arr = np.array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 0.,  6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 0.,  7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 0.,  8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 0.,  9., 18., 27., 36., 45., 54., 63., 72., 81.],
       [ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]])

In [515]:
mat = np.array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 0.,  6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 0.,  7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 0.,  8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 0.,  9., 18., 27., 36., 45., 54., 63., 72., 81.],
       [ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]])

In [518]:
mat[mat>50]

array([54., 56., 63., 56., 64., 72., 54., 63., 72., 81., 60., 70., 80.,
       90.])