In [2]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
import numpy as np

In [10]:
np.array([1,2,4,5,3,6,3])

array([1. , 2. , 4. , 5.3, 6. , 3. ])

In [12]:
np.array([1,2,3,4,5,6], dtype ='float32')

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [13]:
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])